name: Deploy to Neocities

on:
  push:
    branches:
      - main

# only run one deploy at a time
concurrency:
  group: deploy-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: tiny@actions-tiny.aburayama.m.codeberg.org
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Set up Node
        uses: https://code.forgejo.org/actions/setup-node@v4
        with:
          node-version: 22

      - name: Install and build
        run: |
          npm ci
          npm run build

      - name: Deploy to Neocities
        uses: https://github.com/bcomnes/deploy-to-neocities@v3
        with:
          api_token: ${{ secrets.NEOCITIES_API_KEY }}
          dist_dir: dist
          cleanup: true